export enum JourneyType {
  BLOOD_PRESSURE = 'BLOOD_PRESSURE',
  CHOLESTEROL = 'CHOLESTEROL',
  DIABETES = 'DIABETES',
  FULL = 'FULL',
}

export enum JourneyStatus {
  INITIATED = 'INITIATED',
  CONSENT_GIVEN = 'CONSENT_GIVEN',
  PRE_ASSESSMENT_COMPLETE = 'PRE_ASSESSMENT_COMPLETE',
  BOOKED = 'BOOKED',
  IN_PROGRESS = 'IN_PROGRESS',
  RESULTS_READY = 'RESULTS_READY',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum UserRole {
  MEMBER = 'MEMBER',
  PHARMACIST = 'PHARMACIST',
  OPS = 'OPS',
  ADMIN = 'ADMIN',
}

export enum BookingStatus {
  CONFIRMED = 'CONFIRMED',
  CANCELLED = 'CANCELLED',
  COMPLETED = 'COMPLETED',
  NO_SHOW = 'NO_SHOW',
}

export enum ResultStatus {
  NORMAL = 'NORMAL',
  BORDERLINE = 'BORDERLINE',
  HIGH = 'HIGH',
}
